export const SEARCH_KEYWORDS = {
  work: [
    "software",
    "engineer",
    "developer",
    "programming",
    "python",
    "golang",
    "sql",
    "aws",
    "docker",
    "kubernetes",
    "ml",
    "machine",
    "learning",
    "ai",
    "artificial",
    "intelligence",
    "llm",
    "langchain",
    "threat",
    "intelligence",
    "security",
    "cybersecurity",
    "stix",
    "mitre",
    "consulting",
    "architecture",
    "nagra",
    "netstar",
    "barrick",
    "2u",
    "education",
    "automation",
    "cloud",
    "infrastructure",
    "devops",
    "terraform",
    "ansible",
    "postgres",
    "mongodb",
    "neo4j",
    "vectordb",
    "rag",
    "transformers",
    "huggingface",
  ],

  education: [
    "education",
    "degree",
    "university",
    "college",
    "certificate",
    "school",
    "bellevue",
    "arizona",
    "state",
    "masters",
    "associates",
    "full",
    "stack",
    "web",
    "development",
    "perplexity",
    "campus",
    "partner",
    "cyber",
    "saguaro",
    "creative",
    "lab",
    "instructor",
    "research",
    "assistant",
    "comptia",
    "security",
    "eagle",
    "scout",
    "ai",
    "coding",
    "workshop",
    "cybersecurity",
    "python",
    "programming",
    "machine",
    "learning",
    "artificial",
    "intelligence",
  ],

  academia: [
    "research",
    "academic",
    "cybersecurity",
    "education",
    "semantic",
    "web",
    "json",
    "ld",
    "iscap",
    "conference",
    "paper",
    "publication",
    "threat",
    "intelligence",
    "machine",
    "learning",
    "ai",
    "artificial",
    "python",
    "programming",
    "security",
    "university",
    "arizona",
    "pending",
    "final",
    "review",
    "distributed",
    "analytics",
    "competencies",
    "technologies",
  ],

  extracurriculars: [
    "extracurricular",
    "activities",
    "creative",
    "initiatives",
    "tutoring",
    "mentoring",
    "teaching",
    "volunteer",
    "community",
    "leadership",
    "organization",
    "club",
    "society",
    "project",
    "workshop",
    "event",
    "coordination",
    "management",
    "skills",
    "development",
    "training",
    "education",
    "outreach",
  ],

  publicService: [
    "public",
    "service",
    "government",
    "commissioner",
    "planning",
    "zoning",
    "committee",
    "town",
    "sahuarita",
    "municipal",
    "civic",
    "community",
    "volunteer",
    "leadership",
    "policy",
    "development",
    "regulations",
    "compliance",
    "census",
    "bureau",
    "federal",
    "data",
    "collection",
    "analysis",
    "youth",
    "group",
    "eastmark",
    "mesa",
    "arizona",
    "mentoring",
    "guidance",
  ],
} as const

export type TabKeyword = keyof typeof SEARCH_KEYWORDS

export function getKeywordsForTab(tab: TabKeyword): string[] {
  return SEARCH_KEYWORDS[tab] || []
}

export function getAllKeywords(): string[] {
  return Object.values(SEARCH_KEYWORDS).flat()
}

export function findTabsWithKeyword(searchTerm: string): TabKeyword[] {
  const term = searchTerm.toLowerCase().trim()
  if (!term) return []

  return Object.entries(SEARCH_KEYWORDS)
    .filter(([_, keywords]) => keywords.some((keyword) => keyword.includes(term)))
    .map(([tab, _]) => tab as TabKeyword)
}

export function getTabDisplayName(tab: TabKeyword): string {
  const displayNames: Record<TabKeyword, string> = {
    work: "Work Experience",
    education: "Education",
    academia: "Academia",
    extracurriculars: "Extracurriculars",
    publicService: "Public Service",
  }
  return displayNames[tab] || tab
}
