name: Deploy Next.js site to Pages

on:
  push:
    branches: ["master"]   # change to ["main"] if that's your default
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # Correct: Use pnpm/action-setup@v2, not @v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.12.3
          run_install: false

      # Optional: Sanity check
      - name: Check pnpm
        run: pnpm -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Build
        run: pnpm run build

      - name: Export static site
        run: pnpm run export

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out


  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
